name: Build fafafa admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: tongjiann/fafafa-admin
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Date Tag
        id: date
        run: |
          echo "tag=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: send info to ding
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.xiw.world/api/msg/send?msg=fafafa-admin%E9%95%9C%E5%83%8F%E6%8E%A8%E9%80%81%E5%AE%8C%E6%88%90
          log-response: true
          timeout: 20000
