# fafafa 前端 Docker 镜像构建工作流
name: Build fafafa admin

on:
  push:
    branches:
      - main
  # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@9 --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: |
          docker build -t tongjiann/fafafa-admin:latest .

      - name: Push Docker
        run: |
          docker push tongjiann/fafafa-admin:latest

      - name: send info to ding
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.xiw.world/api/msg/send?msg=fafafa-admin%E9%95%9C%E5%83%8F%E6%8E%A8%E9%80%81%E5%AE%8C%E6%88%90
          log-response: true
          timeout: 20000
